name: CI/CD Docker Build and Deploy via BAT on Self-Hosted Runner

on:
  push:
    branches:
      - main # Hoặc branch chính của bạn

jobs:
  build-and-deploy:
    runs-on: [self-hosted, windows] # Đảm bảo runner của bạn có các label này

    # Thiết lập các biến môi trường ở cấp độ job.
    # Các biến này sẽ có sẵn cho tất cả các 'run' steps bên dưới,
    # bao gồm cả môi trường mà deploy.bat được thực thi.
    # Giá trị được lấy từ GitHub Secrets.
    env:
      # Sử dụng tên PROJECT_NAME_FROM_SECRET để tránh xung đột nếu PROJECT_NAME cũng được dùng làm tên image/container
      PROJECT_NAME_FROM_SECRET: ${{ secrets.PROJECT_NAME || 'myfastapiapp-poetry' }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      DB_SERVER: ${{ secrets.DB_SERVER }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_DRIVER: ${{ secrets.DB_DRIVER }}
      # PROJECT_VERSION sẽ được thiết lập động hơn ở step dưới

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Điều này đảm bảo file deploy.bat và Dockerfile có sẵn cho runner

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Vẫn nên có bước này để đảm bảo môi trường build Docker là tối ưu,
        # ngay cả khi lệnh build thực tế nằm trong file .bat


      - name: Execute deployment batch script
        # Gọi file deploy.bat và truyền tham số
        # Tham số 1: Tên cơ sở của image (lấy từ biến môi trường của job)
        # Tham số 2: Tag cụ thể (commit SHA ngắn)
        run: call deploy.bat "%PROJECT_NAME_FROM_SECRET%" "latest"
        shell: cmd # Chỉ định rõ ràng sử dụng cmd.exe để chạy file .bat
        env:
          # Các biến môi trường này sẽ được thiết lập CỤ THỂ cho bước này
          # và sẽ được file deploy.bat sử dụng bên trong lệnh 'docker run -e ...'
          # Chúng ghi đè hoặc bổ sung các biến đã có từ job-level 'env' nếu trùng tên.
          PROJECT_NAME: ${{ env.PROJECT_NAME_FROM_SECRET }} # Sử dụng lại giá trị từ job env
          PROJECT_VERSION: latest # Commit SHA sẽ là version
          # Các biến DB_* khác sẽ được kế thừa từ job-level 'env' block.